version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "website-lambdas"
resolve_s3 = true
s3_prefix = "website-lambdas"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
